name: dev_environment
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - black
  - cookiecutter
  - flake8
  - git
  - git-lfs
  - isort
  - mamba
  - pre-commit
  - snakefmt
  - snakemake
