name: dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - black
  - cookiecutter
  - flake8
  - git
  - git-lfs
  - isort
  - mamba
  - nodejs
  - pre-commit
  - snakefmt
  - snakemake
# partial support for C++ linting utilities
# see also related issue for clang-format discussion
  - cppcheck
# support for R linting utilities
  - r-devtools
  - r-docopt
  - r-lintr
  - r-spelling
  - r-styler
  - r-usethis
