# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a manifest file that contains
# one row per sample. It can be parsed easily via pandas.
manifest: "config/manifest.tsv"
